"""
app/models/run.py — DesignRun and related enums.
Maps directly to the frontend AgentRun / AgentRunSummary types.
"""
from __future__ import annotations

import enum
from typing import Any, Optional

from sqlalchemy import Enum, Float, JSON, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base, TimestampMixin, UUIDMixin


class RunStatus(str, enum.Enum):
    PENDING = "pending"
    QUEUED = "queued"
    RUNNING = "running"
    VALIDATING = "validating"
    SIMULATING = "simulating"
    ANALYZING = "analyzing"
    OPTIMIZING = "optimizing"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"


class PipelineStep(str, enum.Enum):
    REQUIREMENT_PARSING = "requirement_parsing"
    TOPOLOGY_SELECTION = "topology_selection"
    NETLIST_GENERATION = "netlist_generation"
    VALIDATION = "validation"
    SIMULATION_RUN = "simulation_run"
    METRIC_EXTRACTION = "metric_extraction"
    MONTE_CARLO = "monte_carlo"
    OPTIMIZATION_LOOP = "optimization_loop"
    RECOMMENDATION_READY = "recommendation_ready"


class DesignRun(UUIDMixin, TimestampMixin, Base):
    """Top-level design run — the primary entity the frontend works with."""
    __tablename__ = "design_runs"

    # Status / correlation
    status: Mapped[str] = mapped_column(String(32), default=RunStatus.PENDING, index=True)
    correlation_id: Mapped[str] = mapped_column(String(36), default="", index=True)
    current_step: Mapped[Optional[str]] = mapped_column(String(64), nullable=True)

    # Requirements (stored as JSON, mirrors DesignRequirement TS type)
    requirement: Mapped[dict[str, Any]] = mapped_column(JSON, nullable=False)

    # Design summary (generated by AI, mirrors DesignSummary TS type)
    design_summary: Mapped[dict[str, Any] | None] = mapped_column(JSON, nullable=True)

    # Pipeline step progress (list of AgentStep JSON objects)
    steps: Mapped[list[dict[str, Any]]] = mapped_column(JSON, default=list)

    # Timing
    started_at: Mapped[Optional[str]] = mapped_column(String(32), nullable=True)
    completed_at: Mapped[Optional[str]] = mapped_column(String(32), nullable=True)
    total_duration_ms: Mapped[Optional[int]] = mapped_column(nullable=True)

    # Error info
    error_message: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    error_code: Mapped[Optional[str]] = mapped_column(String(64), nullable=True)

    # Relationships
    iterations: Mapped[list["DesignIteration"]] = relationship(  # noqa: F821
        "DesignIteration", back_populates="run", cascade="all, delete-orphan",
        order_by="DesignIteration.iteration_number"
    )
    netlists: Mapped[list["GeneratedNetlist"]] = relationship(  # noqa: F821
        "GeneratedNetlist", back_populates="run", cascade="all, delete-orphan"
    )
    simulation_jobs: Mapped[list["SimulationJob"]] = relationship(  # noqa: F821
        "SimulationJob", back_populates="run", cascade="all, delete-orphan"
    )
    candidates: Mapped[list["CandidateDesign"]] = relationship(  # noqa: F821
        "CandidateDesign", back_populates="run", cascade="all, delete-orphan",
        order_by="CandidateDesign.rank"
    )
    messages: Mapped[list["AgentMessage"]] = relationship(  # noqa: F821
        "AgentMessage", back_populates="run", cascade="all, delete-orphan",
        order_by="AgentMessage.created_at"
    )
    monte_carlo_runs: Mapped[list["MonteCarloRun"]] = relationship(  # noqa: F821
        "MonteCarloRun", back_populates="run", cascade="all, delete-orphan"
    )
    artifacts: Mapped[list["ArtifactFile"]] = relationship(  # noqa: F821
        "ArtifactFile", back_populates="run", cascade="all, delete-orphan"
    )
