"""initial_schema

Revision ID: b6ab12249bd8
Revises: 
Create Date: 2026-03-09 22:32:56.646896

"""
from __future__ import annotations
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6ab12249bd8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('design_runs',
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('correlation_id', sa.String(length=36), nullable=False),
    sa.Column('current_step', sa.String(length=64), nullable=True),
    sa.Column('requirement', sa.JSON(), nullable=False),
    sa.Column('design_summary', sa.JSON(), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.String(length=32), nullable=True),
    sa.Column('completed_at', sa.String(length=32), nullable=True),
    sa.Column('total_duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_design_runs_correlation_id'), 'design_runs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_design_runs_id'), 'design_runs', ['id'], unique=False)
    op.create_index(op.f('ix_design_runs_status'), 'design_runs', ['status'], unique=False)
    op.create_table('playground_sessions',
    sa.Column('user_session_id', sa.String(length=128), nullable=False),
    sa.Column('canvas_state', sa.JSON(), nullable=False),
    sa.Column('command_history', sa.JSON(), nullable=False),
    sa.Column('linked_run_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playground_sessions_id'), 'playground_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_playground_sessions_user_session_id'), 'playground_sessions', ['user_session_id'], unique=False)
    op.create_table('agent_messages',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=True),
    sa.Column('action_data', sa.JSON(), nullable=True),
    sa.Column('pipeline_step', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['design_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_messages_id'), 'agent_messages', ['id'], unique=False)
    op.create_index(op.f('ix_agent_messages_run_id'), 'agent_messages', ['run_id'], unique=False)
    op.create_table('artifact_files',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('file_type', sa.String(length=64), nullable=False),
    sa.Column('file_name', sa.String(length=256), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['design_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifact_files_id'), 'artifact_files', ['id'], unique=False)
    op.create_index(op.f('ix_artifact_files_run_id'), 'artifact_files', ['run_id'], unique=False)
    op.create_table('candidate_designs',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('topology_name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('gain_db', sa.Float(), nullable=True),
    sa.Column('bandwidth_mhz', sa.Float(), nullable=True),
    sa.Column('phase_margin_deg', sa.Float(), nullable=True),
    sa.Column('power_mw', sa.Float(), nullable=True),
    sa.Column('noise_nv_sqrt_hz', sa.Float(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('selection_reason', sa.Text(), nullable=True),
    sa.Column('scores_detail', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['design_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_designs_id'), 'candidate_designs', ['id'], unique=False)
    op.create_index(op.f('ix_candidate_designs_run_id'), 'candidate_designs', ['run_id'], unique=False)
    op.create_table('design_iterations',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('iteration_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('parameter_changes', sa.JSON(), nullable=False),
    sa.Column('metric_deltas', sa.JSON(), nullable=False),
    sa.Column('targets_met_count', sa.Integer(), nullable=False),
    sa.Column('total_targets', sa.Integer(), nullable=False),
    sa.Column('all_targets_met', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('started_at', sa.String(length=32), nullable=True),
    sa.Column('completed_at', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['design_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_design_iterations_id'), 'design_iterations', ['id'], unique=False)
    op.create_index(op.f('ix_design_iterations_run_id'), 'design_iterations', ['run_id'], unique=False)
    op.create_table('monte_carlo_runs',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('parameter_variations', sa.JSON(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('yield_percent', sa.Float(), nullable=True),
    sa.Column('failed_samples', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.String(length=32), nullable=True),
    sa.Column('completed_at', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['design_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monte_carlo_runs_id'), 'monte_carlo_runs', ['id'], unique=False)
    op.create_index(op.f('ix_monte_carlo_runs_run_id'), 'monte_carlo_runs', ['run_id'], unique=False)
    op.create_table('playground_commands',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('raw_input', sa.Text(), nullable=False),
    sa.Column('interpreted_command', sa.JSON(), nullable=True),
    sa.Column('canvas_patches', sa.JSON(), nullable=False),
    sa.Column('agent_response', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['playground_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playground_commands_id'), 'playground_commands', ['id'], unique=False)
    op.create_index(op.f('ix_playground_commands_session_id'), 'playground_commands', ['session_id'], unique=False)
    op.create_table('generated_netlists',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('iteration_id', sa.String(length=36), nullable=True),
    sa.Column('raw_spice', sa.Text(), nullable=False),
    sa.Column('format', sa.String(length=32), nullable=False),
    sa.Column('generated_at', sa.String(length=32), nullable=False),
    sa.Column('generation_attempt', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['iteration_id'], ['design_iterations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['design_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_netlists_id'), 'generated_netlists', ['id'], unique=False)
    op.create_index(op.f('ix_generated_netlists_run_id'), 'generated_netlists', ['run_id'], unique=False)
    op.create_table('simulation_jobs',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('iteration_id', sa.String(length=36), nullable=True),
    sa.Column('netlist_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('stdout', sa.Text(), nullable=True),
    sa.Column('stderr', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.String(length=32), nullable=True),
    sa.Column('completed_at', sa.String(length=32), nullable=True),
    sa.Column('container_id', sa.String(length=64), nullable=True),
    sa.Column('docker_image', sa.String(length=128), nullable=True),
    sa.Column('workspace_path', sa.String(length=512), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['iteration_id'], ['design_iterations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['netlist_id'], ['generated_netlists.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['design_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_jobs_id'), 'simulation_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_simulation_jobs_run_id'), 'simulation_jobs', ['run_id'], unique=False)
    op.create_index(op.f('ix_simulation_jobs_status'), 'simulation_jobs', ['status'], unique=False)
    op.create_table('validation_issues',
    sa.Column('netlist_id', sa.String(length=36), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('node_id', sa.String(length=128), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['netlist_id'], ['generated_netlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_issues_id'), 'validation_issues', ['id'], unique=False)
    op.create_index(op.f('ix_validation_issues_netlist_id'), 'validation_issues', ['netlist_id'], unique=False)
    op.create_table('simulation_results',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('iteration_id', sa.String(length=36), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('ac_response', sa.JSON(), nullable=False),
    sa.Column('phase_response', sa.JSON(), nullable=False),
    sa.Column('transient_response', sa.JSON(), nullable=False),
    sa.Column('monte_carlo_gain', sa.JSON(), nullable=True),
    sa.Column('monte_carlo_phase_margin', sa.JSON(), nullable=True),
    sa.Column('simulated_at', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['simulation_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_index(op.f('ix_simulation_results_id'), 'simulation_results', ['id'], unique=False)
    op.create_index(op.f('ix_simulation_results_iteration_id'), 'simulation_results', ['iteration_id'], unique=False)
    op.create_index(op.f('ix_simulation_results_run_id'), 'simulation_results', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simulation_results_run_id'), table_name='simulation_results')
    op.drop_index(op.f('ix_simulation_results_iteration_id'), table_name='simulation_results')
    op.drop_index(op.f('ix_simulation_results_id'), table_name='simulation_results')
    op.drop_table('simulation_results')
    op.drop_index(op.f('ix_validation_issues_netlist_id'), table_name='validation_issues')
    op.drop_index(op.f('ix_validation_issues_id'), table_name='validation_issues')
    op.drop_table('validation_issues')
    op.drop_index(op.f('ix_simulation_jobs_status'), table_name='simulation_jobs')
    op.drop_index(op.f('ix_simulation_jobs_run_id'), table_name='simulation_jobs')
    op.drop_index(op.f('ix_simulation_jobs_id'), table_name='simulation_jobs')
    op.drop_table('simulation_jobs')
    op.drop_index(op.f('ix_generated_netlists_run_id'), table_name='generated_netlists')
    op.drop_index(op.f('ix_generated_netlists_id'), table_name='generated_netlists')
    op.drop_table('generated_netlists')
    op.drop_index(op.f('ix_playground_commands_session_id'), table_name='playground_commands')
    op.drop_index(op.f('ix_playground_commands_id'), table_name='playground_commands')
    op.drop_table('playground_commands')
    op.drop_index(op.f('ix_monte_carlo_runs_run_id'), table_name='monte_carlo_runs')
    op.drop_index(op.f('ix_monte_carlo_runs_id'), table_name='monte_carlo_runs')
    op.drop_table('monte_carlo_runs')
    op.drop_index(op.f('ix_design_iterations_run_id'), table_name='design_iterations')
    op.drop_index(op.f('ix_design_iterations_id'), table_name='design_iterations')
    op.drop_table('design_iterations')
    op.drop_index(op.f('ix_candidate_designs_run_id'), table_name='candidate_designs')
    op.drop_index(op.f('ix_candidate_designs_id'), table_name='candidate_designs')
    op.drop_table('candidate_designs')
    op.drop_index(op.f('ix_artifact_files_run_id'), table_name='artifact_files')
    op.drop_index(op.f('ix_artifact_files_id'), table_name='artifact_files')
    op.drop_table('artifact_files')
    op.drop_index(op.f('ix_agent_messages_run_id'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_id'), table_name='agent_messages')
    op.drop_table('agent_messages')
    op.drop_index(op.f('ix_playground_sessions_user_session_id'), table_name='playground_sessions')
    op.drop_index(op.f('ix_playground_sessions_id'), table_name='playground_sessions')
    op.drop_table('playground_sessions')
    op.drop_index(op.f('ix_design_runs_status'), table_name='design_runs')
    op.drop_index(op.f('ix_design_runs_id'), table_name='design_runs')
    op.drop_index(op.f('ix_design_runs_correlation_id'), table_name='design_runs')
    op.drop_table('design_runs')
    # ### end Alembic commands ###
