"""
app/services/playground/canvas_to_netlist.py
Converts a ReactFlow canvas state (nodes + edges) to a valid SPICE netlist.
"""
from __future__ import annotations

from typing import Any


class CanvasToNetlistConverter:
    """
    Generates a SPICE netlist from the playground canvas graph state.
    Nodes become SPICE components; edges become net connections.
    """

    # SPICE line template per component type
    _TEMPLATES: dict[str, str] = {
        "nmos":       "M{name} {d} {g} {s} 0 NMOS W={W}u L={L}u",
        "pmos":       "M{name} {d} {g} {s} vdd PMOS W={W}u L={L}u",
        "npn":        "Q{name} {c} {b} {e} NPN",
        "pnp":        "Q{name} {c} {b} {e} PNP",
        "resistor":   "R{name} {n1} {n2} {R}",
        "capacitor":  "C{name} {n1} {n2} {C}",
        "inductor":   "L{name} {n1} {n2} {L}",
        "diode":      "D{name} {a} {k} DIODE",
        "vsource":    "V{name} {p} {n} DC {V}",
        "isource":    "I{name} {p} {n} DC {I}",
        "ground":     "",      # GND is a node reference, no component line
        "vdd":        "Vvdd vdd 0 DC {VDD}",
        "opamp":      "X{name} {inp} {inn} vdd 0 {out} OPAMP",
    }

    def convert(self, nodes: list[dict], edges: list[dict]) -> tuple[str, dict[str, str]]:
        """
        Returns (netlist_text, node_map) where node_map is {node_id → net_name}.
        """
        # Build net names from edges
        node_map = self._build_node_map(nodes, edges)

        lines = ["* Generated by CircuitAI Playground", ""]

        # Supply lines first
        vdd_val = "1.8"
        for n in nodes:
            if n["data"]["type"] == "vdd":
                vdd_val = str(n["data"]["props"].get("VDD", "1.8"))
        lines.append(f"Vvdd vdd 0 DC {vdd_val}")
        lines.append("")

        counters: dict[str, int] = {}

        for node in nodes:
            node_id = node["id"]
            data = node["data"]
            comp_type: str = data["type"]
            props: dict = data.get("props", {})
            label: str = data.get("label", node_id)

            if comp_type in ("ground", "vdd"):
                continue

            counters[comp_type] = counters.get(comp_type, 0) + 1
            instance_num = counters[comp_type]

            net = node_map.get(node_id, f"net_{node_id}")
            line = self._component_line(comp_type, label, net, props, node_map, node_id)
            if line:
                lines.append(f"* {label}")
                lines.append(line)

        lines += [
            "",
            "*** Analysis ***",
            ".op",
            ".ac dec 100 10 1G",
            ".tran 1n 500n",
            "",
            ".end",
        ]

        return "\n".join(lines), node_map

    def _build_node_map(self, nodes: list[dict], edges: list[dict]) -> dict[str, str]:
        """Assign net names to nodes based on edge connections."""
        net_map: dict[str, str] = {}

        # Named nodes (vdd, ground, input_node, output_node) come first
        special_nets = {"vdd": "vdd", "ground": "0", "input_node": "vin", "output_node": "vout"}
        for n in nodes:
            t = n["data"]["type"]
            if t in special_nets:
                net_map[n["id"]] = special_nets[t]

        # Assign numbered nets by connected component
        net_counter = 1
        for edge in edges:
            src, tgt = edge["source"], edge["target"]
            src_net = net_map.get(src)
            tgt_net = net_map.get(tgt)
            if src_net and not tgt_net:
                net_map[tgt] = src_net
            elif tgt_net and not src_net:
                net_map[src] = tgt_net
            elif not src_net and not tgt_net:
                net_name = f"net_{net_counter}"
                net_counter += 1
                net_map[src] = net_name
                net_map[tgt] = net_name

        # Any remaining unconnected nodes
        for n in nodes:
            if n["id"] not in net_map:
                net_map[n["id"]] = f"floating_{n['id']}"

        return net_map

    def _component_line(
        self,
        comp_type: str,
        label: str,
        primary_net: str,
        props: dict,
        node_map: dict[str, str],
        node_id: str,
    ) -> str:
        name = re.sub(r"[^a-zA-Z0-9_]", "", label) or node_id
        p = props

        simple_map = {
            "resistor":  f"R{name} {primary_net} 0 {p.get('R', '1k')}",
            "capacitor": f"C{name} {primary_net} 0 {p.get('C', '1p')}",
            "inductor":  f"L{name} {primary_net} 0 {p.get('L', '1u')}",
            "vsource":   f"V{name} {primary_net} 0 DC {p.get('V', '1.8')}",
            "isource":   f"I{name} {primary_net} 0 DC {p.get('I', '100u')}",
            "diode":     f"D{name} {primary_net} 0 DIODE",
            "nmos":      f"M{name} {primary_net} {primary_net} 0 0 NMOS W={p.get('W', 10)}u L={p.get('L', 0.5)}u",
            "pmos":      f"M{name} {primary_net} {primary_net} vdd vdd PMOS W={p.get('W', 10)}u L={p.get('L', 0.5)}u",
        }
        return simple_map.get(comp_type, f"* unsupported: {comp_type}")


import re  # noqa: E402 — placed here to avoid circular
